# Generated by Django 5.0.3 on 2024-05-13 22:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('dataNascimento', models.DateField(verbose_name='Data Nascimento')),
                ('ra', models.CharField(max_length=8, verbose_name='RA')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('numeroRegistro', models.CharField(max_length=8, verbose_name='Numero registro')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=8, verbose_name='Senha')),
                ('username', models.CharField(default='null', max_length=30, verbose_name='Nome Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTurma', models.CharField(max_length=8, verbose_name='Codigo Turma')),
                ('dataInicio', models.DateField(verbose_name='Data Inicio')),
                ('descricao', models.CharField(max_length=8, verbose_name='Descricao')),
                ('ano', models.CharField(max_length=2, verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='app.professor')),
                ('id_turma', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
            options={
                'verbose_name': 'Relação Professor / Turma',
            },
        ),
        migrations.CreateModel(
            name='HistoricoMedicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField(max_length=100, verbose_name='Altura')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('imc', models.FloatField(verbose_name='IMC')),
                ('timeStamp', models.DateField(default=django.utils.timezone.now, verbose_name='TS')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno')),
                ('id_turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turma')),
            ],
            options={
                'verbose_name': 'Historico de Mediçõe',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmaAtual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
