# Generated by Django 5.0.3 on 2024-05-13 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Inicio'),
        ),
    ]
