# Generated by Django 5.0.3 on 2024-04-24 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorturma',
            name='id_aluno',
        ),
        migrations.AddField(
            model_name='professorturma',
            name='id_turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
