# Generated by Django 5.0.3 on 2024-04-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_professorturma_id_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='username',
            field=models.CharField(default='null', max_length=30, verbose_name='Nome Usuario'),
        ),
    ]
