# Generated by Django 5.0.3 on 2024-05-13 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_turma_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateField(default=datetime.date(2024, 5, 13), verbose_name='Data Inicio'),
        ),
    ]
