# Generated by Django 5.0.3 on 2024-04-25 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_professor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorturma',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='app.professor'),
        ),
    ]
