# Generated by Django 5.0.3 on 2024-04-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='professore',
        ),
    ]
