# Generated by Django 5.0.3 on 2024-04-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_myuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
