# Generated by Django 5.0.3 on 2024-05-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_professorturma_id_professor'),
        ('app', '0005_delete_myuser'),
    ]

    operations = [
    ]
