# Generated by Django 5.0.3 on 2024-05-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20240503_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicomedicoes',
            options={'verbose_name': 'Historico de Mediçõe'},
        ),
        migrations.AlterModelOptions(
            name='professorturma',
            options={'verbose_name': 'Relação Professor / Turma'},
        ),
        migrations.AddField(
            model_name='historicomedicoes',
            name='id_turma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
