# Generated by Django 5.0.3 on 2024-05-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_historicomedicoes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomedicoes',
            name='id_turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
