# Generated by Django 5.0.3 on 2024-05-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_historicomedicoes_id_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomedicoes',
            name='id_turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turma'),
        ),
    ]
