# Generated by Django 5.0.3 on 2024-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_historicomedicoes_id_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano',
            field=models.CharField(default='1', max_length=2, verbose_name='Ano'),
            preserve_default=False,
        ),
    ]
